# Generated by Django 5.2.6 on 2025-10-08 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostID', models.AutoField(primary_key=True, serialize=False, verbose_name='Post ID')),
                ('Title', models.CharField(max_length=200, verbose_name='Title')),
                ('Description', models.TextField(verbose_name='Description')),
                ('Category', models.CharField(choices=[('tech', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('retail', 'Retail'), ('food', 'Food & Beverage'), ('sustainability', 'Sustainability'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('TargetMarket', models.TextField(blank=True, null=True, verbose_name='Target Market')),
                ('BusinessModel', models.TextField(blank=True, null=True, verbose_name='Business Model')),
                ('FundingNeeds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Funding Needs ($)')),
                ('Status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('UpdatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-CreatedAt'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False, verbose_name='Project ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Type', models.CharField(max_length=100, verbose_name='Type')),
                ('Description', models.TextField(verbose_name='Description')),
                ('URL', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(blank=True, max_length=50, null=True, verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Project Team Member',
                'verbose_name_plural': 'Project Team Members',
            },
        ),
    ]
