# Generated by Django 5.2.6 on 2025-09-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ANumber', models.CharField(max_length=20, unique=True, verbose_name='A-Number')),
                ('Email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('Password', models.CharField(max_length=128, verbose_name='Password')),
                ('FirstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('LastName', models.CharField(max_length=50, verbose_name='Last Name')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
